bind_addresses:
- :8080
video:
  bitrate: 8000000
  framerate: 30
ice_servers:
- urls:
  - stun:stun.l.google.com:19302
  - stun:stun1.l.google.com:19302
tls:
  enabled: true
  cert_file: ./cert.pem
  key_file: ./key.pem
security:
  check_origin: true
  additional_origins: []
auth:
  use_system_auth: true
  hmac_key: ./hmac.key
  token_validity_hours: 24
  users:
  - username: test
    password: abc123
